package compiler.parser;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 05 14:55:11 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MADE_LITERAL = 53;
  public static final int VIOLATION_LITERAL = 26;
  public static final int REVERSE_LITERAL = 45;
  public static final int SHOT_LITERAL = 15;
  public static final int TIME = 85;
  public static final int AST = 82;
  public static final int VS_LITERAL = 39;
  public static final int SHORT_LITERAL = 61;
  public static final int TEAM = 84;
  public static final int ST = 76;
  public static final int OVERTIME_LITERAL = 5;
  public static final int THIRD = 9;
  public static final int JUMP_LITERAL = 38;
  public static final int PERSONAL_LITERAL = 69;
  public static final int REBOUND_LITERAL = 55;
  public static final int RIGHT_PAREN = 88;
  public static final int THREEPT_LITERAL = 36;
  public static final int MISSED_LITERAL = 52;
  public static final int SECOND = 8;
  public static final int FOUL_LITERAL = 33;
  public static final int POSSESSION_LITERAL = 72;
  public static final int GOALTENDING_LITERAL = 67;
  public static final int OUT_LITERAL = 23;
  public static final int LAYUP_LITERAL = 41;
  public static final int BLK = 79;
  public static final int PALMING_LITERAL = 22;
  public static final int OF_LITERAL = 3;
  public static final int PASS_LITERAL = 20;
  public static final int FIRST = 7;
  public static final int ROLL_LITERAL = 74;
  public static final int BY_LITERAL = 64;
  public static final int LOST_LITERAL = 17;
  public static final int DEF = 81;
  public static final int STEAL_LITERAL = 35;
  public static final int PULLUP_LITERAL = 43;
  public static final int CLOCK_LITERAL = 16;
  public static final int BACKCOURT_LITERAL = 32;
  public static final int TURNAROUND_LITERAL = 47;
  public static final int RIGHT_BRAC = 89;
  public static final int LOOSE_LITERAL = 68;
  public static final int CHARGE_LITERAL = 70;
  public static final int TEAM_LITERAL = 13;
  public static final int ASSIST_LITERAL = 56;
  public static final int ILLEGAL_LITERAL = 30;
  public static final int PTS = 78;
  public static final int NUMBER = 91;
  public static final int DRIBBLE_LITERAL = 29;
  public static final int TIMEOUT_LITERAL = 59;
  public static final int START_LITERAL = 2;
  public static final int PLAYER_NAME = 83;
  public static final int SIXTH = 12;
  public static final int SCREEN_LITERAL = 31;
  public static final int THROW_LITERAL = 58;
  public static final int FIFTH = 11;
  public static final int LEFT_PAREN = 86;
  public static final int BANK_LITERAL = 50;
  public static final int GAINS_LITERAL = 40;
  public static final int QUARTER_LITERAL = 4;
  public static final int FREE_LITERAL = 57;
  public static final int TURNOVER_LITERAL = 14;
  public static final int STEP_LITERAL = 25;
  public static final int EOF = 0;
  public static final int PF = 77;
  public static final int DEFENSE_LITERAL = 73;
  public static final int BOUNDS_LITERAL = 24;
  public static final int SHOOTING_LITERAL = 71;
  public static final int RUNNING_LITERAL = 37;
  public static final int TECHNICAL_LITERAL = 66;
  public static final int FOURTH = 10;
  public static final int LEFT_BRAC = 87;
  public static final int error = 1;
  public static final int SECOND_LITERAL = 65;
  public static final int POSS_LITERAL = 27;
  public static final int OFF = 80;
  public static final int COLON = 90;
  public static final int DUNK_LITERAL = 49;
  public static final int REGULAR_LITERAL = 60;
  public static final int BALL_LITERAL = 18;
  public static final int TIP_LITERAL = 44;
  public static final int REPLACED_LITERAL = 63;
  public static final int BAD_LITERAL = 19;
  public static final int DISCONTINUE_LITERAL = 28;
  public static final int TRAVELING_LITERAL = 21;
  public static final int SUBSTITUTION_LITERAL = 62;
  public static final int BLOCK_LITERAL = 54;
  public static final int SLAM_LITERAL = 51;
  public static final int DRIVING_LITERAL = 42;
  public static final int TO = 75;
  public static final int HOOK_LITERAL = 46;
  public static final int OFFENSIVE_LITERAL = 34;
  public static final int FINGER_LITERAL = 48;
  public static final int END_LITERAL = 6;
}

